apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: {{name}}
  namespace: team-oebs
  labels:
    team: team-oebs
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
     {{key}}: {{value}}
  {{/each}}
  acl:
    - team: team-oebs
      application: {{app_name_oebs}}
      access: readwrite
