pool: nav-prod
name: faktura-status.v1
config:
  cleanupPolicy: delete
  minimumInSyncReplicas: 1
  partitions: 1
  replication: 2
  retentionBytes: -1
  retentionHours: 672 # 4 Uker
app_name_melosys: faktureringskomponenten
app_name_oebs: oebs-melosys-api
app_name_kafka_manager: teammelosys-kafka-manager
app_name_kafka_manager_oebs: team-oebs-kafka-manager
