apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: {{name}}
  namespace: team-oebs
  labels:
    team: team-oebs
spec:
  pool: {{pool}}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 2
    retentionBytes: -1
    retentionHours: 168
  acl:
    - team: team-oebs
      application: {{app_name_oebs}}
      access: readwrite
    - team: team-oebs
      application: {{app_name_kafka_manager_oebs}}
      access: readwrite
