name: Deploy

on:
  push:
    branches: main
    paths:
      - kafka/**
      - .github/workflows/deploy-kafka.yaml
      - '!kafka/README.md'
  workflow_dispatch:
    inputs:
      topics:
        description: >
          Comma-separated list of topics to deploy.
          Available: faktura-import.dlq.v1, faktura-status.v1,
          melosys-q2-faktura.v1, melosys-q2-status.v1, ordre-oebs.v1, test-faktura.v1
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      emptyMatrix: ${{ steps.set-matrix.outputs.emptyMatrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: set-matrix
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            MATRIX="${{ github.event.inputs.topics }}"
          else
            MATRIX=$(git diff-tree --diff-filter=d --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.sha }} | grep kafka/ | grep -v README.md | cut -d '/' -f 2 | sort -u | paste -d',' -s)
          fi
          echo Matrix is $MATRIX
          if [[  -z "${MATRIX// }" ]]; then
            echo "Empty matrix"
            echo "emptyMatrix=true" >> $GITHUB_OUTPUT
            echo "matrix=[]" >> $GITHUB_OUTPUT
          else
            JSON=$(jq -c -n --arg v $MATRIX '{"topic": $v|split(",")}')
            echo "matrix: $JSON"
            echo "matrix=$JSON" >> $GITHUB_OUTPUT
            echo "emptyMatrix=false" >> $GITHUB_OUTPUT
          fi
  deploy:
    needs: setup-matrix
    runs-on: ubuntu-latest
    if: needs.setup-matrix.outputs.emptyMatrix == 'false'
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: deploy to u1
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: kafka/${{ matrix.topic }}/topic.yaml
          VARS: kafka/${{ matrix.topic }}/u1-vars.yaml
          PRINT_PAYLOAD: true
      - name: deploy to q1
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: kafka/${{ matrix.topic }}/topic.yaml
          VARS: kafka/${{ matrix.topic }}/q1-vars.yaml
          PRINT_PAYLOAD: true
      - name: deploy to t1
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: kafka/${{ matrix.topic }}/topic.yaml
          VARS: kafka/${{ matrix.topic }}/t1-vars.yaml
          PRINT_PAYLOAD: true
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: kafka/${{ matrix.topic }}/topic-prod.yaml
          VARS: kafka/${{ matrix.topic }}/prod-vars.yaml
          PRINT_PAYLOAD: true
