name: Deploy-q2

on:
  workflow_dispatch: {}   
  push:
    branches: [main]
    paths:
      - 'kafka/**/*q2*'
      - '.github/workflows/q2-deploy.yaml'

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      emptyMatrix: ${{ steps.set-matrix.outputs.emptyMatrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: set-matrix
        shell: bash
        run: |
          MATRIX=$(git diff-tree --diff-filter=d --no-commit-id --name-only -r "${{ github.event.before }}" "${{ github.sha }}" \
            | grep '^kafka/' | grep -v 'README.md' | cut -d '/' -f 2 | sort -u | paste -d',' -s)

          echo "Matrix is: $MATRIX"
          if [[ -z "${MATRIX// }" ]]; then
            echo "emptyMatrix=true" >> "$GITHUB_OUTPUT"
            echo 'matrix=[]' >> "$GITHUB_OUTPUT"
          else
            JSON=$(jq -c -n --arg v "$MATRIX" '{"topic": ($v|split(","))}')
            echo "matrix=$JSON" >> "$GITHUB_OUTPUT"
            echo "emptyMatrix=false" >> "$GITHUB_OUTPUT"
          fi

  deploy:
    needs: setup-matrix
    runs-on: ubuntu-latest
    if: needs.setup-matrix.outputs.emptyMatrix == 'false'
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: deploy to q2
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: kafka/${{ matrix.topic }}/topic.yaml
          VARS: kafka/${{ matrix.topic }}/q2-vars.yaml
          PRINT_PAYLOAD: true
